/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.tijanja.websocket;

import javax.json.JsonObject;
import javax.websocket.*;
import javax.websocket.server.ServerEndpoint;

import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonParser;

import java.io.IOException;
import java.sql.Connection;
import java.util.ArrayList;
import java.util.List;


@ServerEndpoint( "/endpoint")
public class HelloWorldEndpoint {

    List<Session> clientSession;
    Gson gson;
    Connection conn;

    public HelloWorldEndpoint() {
        System.out.println("class loaded " + this.getClass());
        clientSession = new ArrayList<>();
        gson = new Gson();
        conn = ConfigDB.connectDB();
        
    }

    @OnOpen
    public void onOpen(Session session) {
        System.out.printf("Session opened, id: %s%n", session.getId());
        clientSession.add(session);
        try {
            session.getBasicRemote().sendText("{'action':'connected','sessionId':'"+session.getId()+"'}");
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    @OnMessage
    public void onMessage(String message, Session session) {
        System.out.printf("Message received. Session id: %s Message: %s%n",session.getId(), message);
        JsonParser parser = new JsonParser();
        com.google.gson.JsonObject jsonObj =(com.google.gson.JsonObject) parser.parse(message);
        
        switch(jsonObj.getAsJsonObject("action").toString())
        {
            case "login":{
                System.out.print(message);
                //conn.prepareStatement("Insert into user Values('',)")
            }
        }
    }

    @OnError
    public void onError(Throwable e) {
        e.printStackTrace();
    }

    @OnClose
    public void onClose(Session session) {
        System.out.printf("Session closed with id: %s%n", session.getId());
    }
}
